database:
  host: localhost
  port: 3306
  username: root
  password: 123456
  name: yzw

interval:
  seconds: 1

proxy:
  pool_url: "http://127.0.0.1:5010"
  enabled: true
  test_url: "https://www.baidu.com"
  test_timeout: 10
  backup_proxies:
    - "127.0.0.1:7890"
    - "127.0.0.1:1080"
    - "127.0.0.1:8080"
